sudo: required

language: python
python:
- 2.7
- 3.3
- 3.4
- 3.5
- 3.6

before_script:
  - sh ./travis/init.sh
  - pip install codecov

script:
  - nosetests --with-coverage --cover-package=imgkit --where test imgkit_test.py
  - codecov

before_deploy: sh ./travis/pandoc.sh

deploy:
  provider: pypi
  user: jack614
  password:
    secure: zzVWyvpe5oKzfBpm56bed6pruG7+DwW6KsG4zNACfrfR9CKYZUH4JxaTA6kEdiIZX9Syb+mBXg4yobiueJ2aMSQ78VQbUR9R/ULjDkBPyJjs3jqY3ekpbxOHAIDZ4q3cSfjt55veMy1eJ1ojhhwUkdzm2n0O+rsPd4njNxuVxQ2tgHSoId6gvv2X5f7m6qY5Kgs66A1x+Z8amaHeD16w5f33paYNTvIfQDvlQJrljtQ+b4zgeln8PfJucXkjU1BnEnBKZgc+Ii+mnFgIVFJA3WnuszmupG17Pbh2EhR/GWSlVZAalNIU/zzW1cgOG1h0hISJOl1J+Y4Fi5qfs7pWOv3yz0xnD1RJ8GlWnEhrP6VPbcBQSmjueJTkTN5lH1xOrAto0D1saZo2RHEp78uGTZlvjFTCWfkk4/V7QYtRVY70LqUYs6ay0KWZ2BAQvd0nk7C1UA3cc5vQt2XTHdr5DPRp+QV+g76vfjI03EzDYCxNXDNbg2CSn8wffux+YlOrqvLd1kjwyyRuDJSHrtkpzk6tygSY1UU541OYsl5y02zFZQARIoELsz6wx/IfAYwBlBT0SYH/a48aYh2bVq/0cXrXcUsR8haf2pPo2CzJZitcRAOis1qVM42b+cTBmO1mo1LW/91p26ldZtVqpXxdHQqGZQIBHunkE5SfD/iORLo=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: jarrekk/imgkit

notifications:
  email: me@jarrekk.com
